import heroImage from '../assets/images/hero-image-2.jpg';

export const featuredRecipes = [
  {
    id: 1,
    slug: 'ghormeh-sabzi',
    image: heroImage,
    title: 'قورمه سبزی',
    description: 'خورشت اصیل ایرانی با سبزی معطر، لوبیا قرمز و گوشت گوسفندی، طعمی فراموش‌نشدنی',
    rating: 4.8,
    time: 180,
    difficulty: 'متوسط',
  },
  {
    id: 2,
    slug: 'zereshk-polo',
    image: heroImage,
    title: 'زرشک پلو با مرغ',
    description: 'پلوی مجلسی ایرانی با زرشک، زعفران و مرغ طلایی برشته',
    rating: 4.7,
    time: 120,
    difficulty: 'آسان',
  },
  {
    id: 3,
    slug: 'kabab-koubideh',
    image: heroImage,
    title: 'کباب کوبیده',
    description: 'کباب کلاسیک ایرانی از گوشت چرخ‌کرده با پیاز و ادویه مخصوص',
    rating: 4.9,
    time: 45,
    difficulty: 'متوسط',
  },
  {
    id: 4,
    slug: 'fesenjan',
    image: heroImage,
    title: 'فسنجان',
    description: 'خورشت مجلسی با گردو و رب انار، ترکیبی بی‌نظیر از طعم‌های شیرین و ترش',
    rating: 4.6,
    time: 150,
    difficulty: 'سخت',
  },
  {
    id: 5,
    slug: 'mirza-ghasemi',
    image: heroImage,
    title: 'میرزا قاسمی',
    description: 'غذای گیلانی با بادمجان کبابی، گوجه، سیر و تخم‌مرغ',
    rating: 4.5,
    time: 60,
    difficulty: 'آسان',
  },
  {
    id: 6,
    slug: 'tahchin',
    image: heroImage,
    title: 'ته‌چین مرغ',
    description: 'ته‌چین زعفرانی با مرغ، ماست و تخم‌مرغ با پوسته طلایی و برشته',
    rating: 4.8,
    time: 120,
    difficulty: 'متوسط',
  },
];