const recipeLists = {
  trending: [
    {
      id: 101,
      slug: "ghormeh-sabzi",
      title: "قورمه سبزی",
      description: "خورشت اصیل ایرانی",
      image: "/src/assets/images/hero-image-2.jpg",
      rating: 4.8,
      time: 180,
      difficulty: "متوسط",
    },
    {
      id: 102,
      slug: "kabab-koubideh",
      title: "کباب کوبیده",
      description: "کباب کلاسیک ایرانی",
      image: "/src/assets/images/iranian.jpg",
      rating: 4.9,
      time: 45,
      difficulty: "متوسط",
    },
    {
      id: 103,
      slug: "zereshk-polo",
      title: "زرشک پلو",
      description: "پلوی مجلسی با مرغ",
      image: "/src/assets/images/hero-image-2.jpg",
      rating: 4.7,
      time: 120,
      difficulty: "آسان",
    },
    {
      id: 104,
      slug: "fesenjan",
      title: "فسنجان",
      description: "خورشت گردو و رب انار",
      image: "/src/assets/images/iranian.jpg",
      rating: 4.9,
      time: 150,
      difficulty: "سخت",
    },
    {
      id: 105,
      slug: "spinach-omelette",
      title: "املت اسفناج",
      description: "صبحانه سریع",
      image: "/src/assets/images/breakfast.jpg",
      rating: 4.2,
      time: 15,
      difficulty: "آسان",
    },
    {
      id: 106,
      slug: "carrot-cake",
      title: "کیک هویج",
      description: "کیک خوشمزه",
      image: "/src/assets/images/dessert.jpg",
      rating: 4.7,
      time: 90,
      difficulty: "متوسط",
    },
  ],
  new: [
    {
      id: 201,
      slug: "tahchin",
      title: "ته‌چین مرغ",
      description: "ته‌چین زعفرانی",
      image: "/src/assets/images/hero-image-2.jpg",
      rating: 4.5,
      time: 100,
      difficulty: "متوسط",
    },
    {
      id: 202,
      slug: "strawberry-smoothie",
      title: "اسموتی توت فرنگی",
      description: "نوشیدنی خنک",
      image: "/src/assets/images/drink.jpg",
      rating: 4.3,
      time: 10,
      difficulty: "آسان",
    },
    {
      id: 203,
      slug: "margherita-pizza",
      title: "پیتزا مارگاریتا",
      description: "پیتزای کلاسیک",
      image: "/src/assets/images/fastfood.jpg",
      rating: 4.6,
      time: 40,
      difficulty: "آسان",
    },
    {
      id: 204,
      slug: "barley-soup",
      title: "سوپ جو",
      description: "سوپ گرم و مقوی",
      image: "/src/assets/images/soup.jpg",
      rating: 4.4,
      time: 60,
      difficulty: "آسان",
    },
  ],
  category: [
    {
      id: 301,
      slug: "ghormeh-sabzi",
      title: "قورمه سبزی",
      description: "خورشت اصیل",
      image: "/src/assets/images/hero-image-2.jpg",
      rating: 4.8,
      time: 180,
      difficulty: "متوسط",
    },
    {
      id: 302,
      slug: "fesenjan",
      title: "فسنجان",
      description: "خورشت گردو و رب انار",
      image: "/src/assets/images/iranian.jpg",
      rating: 4.9,
      time: 150,
      difficulty: "سخت",
    },
    {
      id: 303,
      slug: "kabab-koubideh",
      title: "کباب کوبیده",
      description: "کباب کلاسیک",
      image: "/src/assets/images/iranian.jpg",
      rating: 4.9,
      time: 45,
      difficulty: "متوسط",
    },
    {
      id: 304,
      slug: "mirza-ghasemi",
      title: "میرزا قاسمی",
      description: "غذای گیلانی",
      image: "/src/assets/images/iranian.jpg",
      rating: 4.5,
      time: 60,
      difficulty: "آسان",
    },
  ],
};

export default recipeLists;
